# -*- coding: utf-8 -*-
"""BerlinV2XRegression_EAAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vax6ECdOtgf21XLPHkHGZi4Qy1PYwlEN

##Data Loading
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
cell_df = pd.read_parquet('/content/drive/MyDrive/Datasets/Berlin_v2x/cellular_dataframe.parquet')
#Preprocess the data
#Convert the datarate for MBps
cell_df['datarate']=cell_df['datarate']/1e6

"""## Problem setup - filters


"""

print(cell_df.shape)#Shape of the Original Dataset

#filter for downlink and uses datarate as qos measurement - the original dataset has downlink and uplink for direction, and for measured_qos has 'datarate' and 'delay'
filtered_data = cell_df.query("direction == 'downlink' & measured_qos == 'datarate'")
print(filtered_data.shape)#Show shape of the Filtered Data

# Remove incomplete measurements without datarate
filtered_data = filtered_data.dropna(subset='datarate')
print(filtered_data.shape)#Show shape of the Filtered Data

#Remove stationary measurements (speed=0)
filtered_data = filtered_data.query("speed_kmh != 0")
print(filtered_data.shape)#Show shape of the Filtered Data

#Remove incomplete measurements without speed (speed=NaN)
filtered_data = filtered_data.dropna(subset='speed_kmh')
print(filtered_data.shape)#Show shape of the Filtered Data

#Filter for A3D scenario - just to confirm, but the filters above already did that
filtered_data = filtered_data.query("scenario == 'A3D'")
print(filtered_data.shape)#Show shape of the Filtered Data

"""### Create datasets for each environment (area)"""

data_avenue= filtered_data.query("area == 'Avenue'")
print(data_avenue.shape)
data_park=filtered_data.query("area == 'Park'")
print(data_park.shape)
data_residential=filtered_data.query("area == 'Residential'")
print(data_residential.shape)
data_highway=filtered_data.query("area == 'Highway'")
print(data_highway.shape)
data_tunnel=filtered_data.query("area == 'Tunnel'")
print(data_tunnel.shape)

"""## Feature selection and Split"""

qos_column = 'datarate'

feature_columns = [
    #PHY features
     'PCell_RSRP_max',
     'PCell_RSRQ_max',
     'PCell_RSSI_max',
     'PCell_SNR_1',
     'PCell_SNR_2',
     'SCell_RSRP_max',
     'SCell_RSRQ_max',
     'SCell_RSSI_max',
     'SCell_SNR_1',
     'SCell_SNR_2',

    #Physical Shared Channels and Radio Resource Control (RRC)
     'PCell_Downlink_Num_RBs',
     'PCell_Downlink_TB_Size',
     'PCell_Downlink_Average_MCS',
     'PCell_Downlink_bandwidth_MHz',
     'PCell_Cell_Identity',
     'PCell_freq_MHz',
     'SCell_Downlink_Num_RBs',
     'SCell_Downlink_TB_Size',
     'SCell_Downlink_Average_MCS',
     'SCell_Downlink_bandwidth_MHz',
     'SCell_Cell_Identity',
     'SCell_freq_MHz'
     ]

used_features = len(feature_columns)
print(f"The implementation uses {used_features} features")

"""### Feature selection - each environment"""

#Filter for each environment

x_avenue,  y_avenue = data_avenue[feature_columns], data_avenue[qos_column]
x_park,  y_park = data_park[feature_columns], data_park[qos_column]
x_residential,  y_residential = data_residential[feature_columns], data_residential[qos_column]
x_highway,  y_highway = data_highway[feature_columns], data_highway[qos_column]
x_tunnel, y_tunnel = data_tunnel[feature_columns], data_tunnel[qos_column]

x_avenue = x_avenue.fillna(0)
x_park = x_park.fillna(0)
x_residential = x_residential.fillna(0)
x_highway = x_highway.fillna(0)
x_tunnel = x_tunnel.fillna(0)

#Separating data in Training, validation and test
from sklearn.model_selection import train_test_split
train_ratio = 0.80
validation_ratio = 0.10
test_ratio = 0.10


#Avenue
x_traina,x_testav,y_traina,y_testav=train_test_split(x_avenue,y_avenue,test_size=1 - train_ratio,random_state=0)
x_vala,x_testa,y_vala,y_testa=train_test_split(x_testav,y_testav,test_size=test_ratio/(test_ratio + validation_ratio),random_state=0)


#Residential
x_trainr,x_testrv,y_trainr,y_testrv=train_test_split(x_residential,y_residential,test_size=1 - train_ratio,random_state=0)
x_valr,x_testr,y_valr,y_testr=train_test_split(x_testrv,y_testrv,test_size=test_ratio/(test_ratio + validation_ratio),random_state=0)


#Park
x_trainp,x_testpv,y_trainp,y_testpv=train_test_split(x_park,y_park,test_size=1 - train_ratio,random_state=0)
x_valp,x_testp,y_valp,y_testp=train_test_split(x_testpv,y_testpv,test_size=test_ratio/(test_ratio + validation_ratio),random_state=0)

#Highway
x_trainh,x_testhv,y_trainh,y_testhv=train_test_split(x_highway,y_highway,test_size=1 - train_ratio,random_state=0)
x_valh,x_testh,y_valh,y_testh=train_test_split(x_testhv,y_testhv,test_size=test_ratio/(test_ratio + validation_ratio),random_state=0)

#Tunnel
x_traint,x_testtv,y_traint,y_testtv=train_test_split(x_tunnel,y_tunnel,test_size=1 - train_ratio,random_state=0)
x_valt,x_testt,y_valt,y_testt=train_test_split(x_testtv,y_testtv,test_size=test_ratio/(test_ratio + validation_ratio),random_state=0)

#Total data - separated per environment

x_trainarea=pd.concat([x_traina,x_trainp,x_trainr,x_trainh,x_traint])
print(x_trainarea.shape)
x_valarea=pd.concat([x_vala,x_valp,x_valr,x_valh,x_valt])
print(x_valarea.shape)
x_testarea=pd.concat([x_testa,x_testp,x_testr,x_testh,x_testt])
print(x_testarea.shape)
y_trainarea=pd.concat([y_traina,y_trainp,y_trainr,y_trainh,y_traint])
y_valarea=pd.concat([y_vala,y_valp,y_valr,y_valh,y_valt])
y_testarea=pd.concat([y_testa,y_testp,y_testr,y_testh,y_testt])

"""## Part 1 - Hyperparameter Tuning for Random Forest

### Study Number of Depth
"""

#Study Number of depth
import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error

ndepth=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
reps=5#number of repetitions
shapetest=(len(ndepth),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição

j=0
for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for ndep in ndepth:
        rf = RandomForestRegressor(max_depth=ndep,max_features=int(used_features/3))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i]} segundos para predizer com o modelo")

        print('Metrics for RF: '+'max_depth='+str(ndep))
        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i]))
        MAErf[i,j]=mean_absolute_error(y_valarea,y_pred)#evaluate MAE (validação)
        print('MAE='+str(MAErf[i]))
        RMSErf[i,j]=mean_squared_error(y_valarea,y_pred, squared=False)#evaluate RMSE (validação)
        print('RMSE='+str(RMSErf[i]))
        #Save the model with pickle
#        with open(modelspath+'ndepth_'+str(ndep)+'rep'+str(j)+'.pkl', 'wb') as f:
#          pickle.dump(rf, f)
        i=i+1

print("R2 Score: ")
for i in range(len(ndepth)):
  for j in range(reps):
    print(r2_scorerf[i,j])

print("MAE: ")
for i in range(len(ndepth)):
  for j in range(reps):
    print(MAErf[i,j])

print("RMSErf: ")
for i in range(len(ndepth)):
  for j in range(reps):
   print(RMSErf[i,j])

print("Tempo de Treinamento: ")
for i in range(len(ndepth)):
  for j in range(reps):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for i in range(len(ndepth)):
  for j in range(reps):
    print(temppred[i,j])

"""###Study Number of Estimators"""

#Study Number of Estimators

import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error

nestimators=[50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000]#number of estimators
reps=5#number of repetitions
shapetest=(len(nestimators),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição

j=0
for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for nest in nestimators:
        rf = RandomForestRegressor(n_estimators=nest,max_features=int(used_features/3))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i]} segundos para predizer com o modelo")


        print('Metrics for RF: '+'nestimators='+str(nest))
        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i]))
        MAErf[i,j]=mean_absolute_error(y_valarea,y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i]))
        RMSErf[i,j]=mean_squared_error(y_valarea,y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i]))
        #Save the model with pickle
 #       with open(modelspath+'nestimators_'+str(nest)+'rep'+str(j)+'.pkl', 'wb') as f:
 #         pickle.dump(rf, f)
        i=i+1

print("R2 Score: ")
for i in range(len(nestimators)):
  for j in range(reps):
    print(r2_scorerf[i,j])

print("MAE: ")
for i in range(len(nestimators)):
  for j in range(reps):
    print(MAErf[i,j])

print("RMSErf: ")
for i in range(len(nestimators)):
  for j in range(reps):
   print(RMSErf[i,j])

print("Tempo de Treinamento: ")
for i in range(len(nestimators)):
  for j in range(reps):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for i in range(len(nestimators)):
  for j in range(reps):
    print(temppred[i,j])

"""###Study Max Features"""

#Study Max Features

import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error

maxfeatures=["log2", "sqrt", 5, 6, int(used_features/3), 8, 9, 10, 11, 12,13,14,15,16,17,18,19,20,21,22]
reps=5#number of repetitions
shapetest=(len(maxfeatures),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0
for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for max in maxfeatures:
        rf = RandomForestRegressor(max_features=max)
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i]} segundos para predizer com o modelo")


        print('Metrics for RF: '+'max_features='+str(max))
        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i]))
        MAErf[i,j]=mean_absolute_error(y_valarea,y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i]))
        RMSErf[i,j]=mean_squared_error(y_valarea,y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i]))
        #Save the model with pickle
#        with open(modelspath+'max_feat_'+str(max)+'rep'+str(j)+'.pkl', 'wb') as f:
#          pickle.dump(rf, f)
        i=i+1

print("R2 Score: ")
for i in range(len(maxfeatures)):
  for j in range(reps):
    print(r2_scorerf[i,j])

print("MAE: ")
for i in range(len(maxfeatures)):
  for j in range(reps):
    print(MAErf[i,j])

print("RMSErf: ")
for i in range(len(maxfeatures)):
  for j in range(reps):
   print(RMSErf[i,j])



print("Tempo de Treinamento: ")
for i in range(len(maxfeatures)):
  for j in range(reps):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for i in range(len(maxfeatures)):
  for j in range(reps):
    print(temppred[i,j])

"""###Study Max Samples"""

#Study Max Samples

import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error

maxsamples=[0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]
reps=5#number of repetitions
shapetest=(len(maxsamples),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição

j=0
for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for maxs in maxsamples:
        rf = RandomForestRegressor(max_samples=maxs,max_features=int(used_features/3))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i]} segundos para predizer com o modelo")

        print('Metrics for RF: '+'max_samples='+str(maxs))
        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i]))
        MAErf[i,j]=mean_absolute_error(y_valarea,y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i]))
        RMSErf[i,j]=mean_squared_error(y_valarea,y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i]))

        #Save the model with pickle
#        with open(modelspath+'max_samples_'+str(maxs)+'rep'+str(j)+'.pkl', 'wb') as f:
#          pickle.dump(rf, f)
        i=i+1

print("R2 Score: ")
for i in range(len(maxsamples)):
  for j in range(reps):
    print(r2_scorerf[i,j])

print("MAE: ")
for i in range(len(maxsamples)):
  for j in range(reps):
    print(MAErf[i,j])

print("RMSErf: ")
for i in range(len(maxsamples)):
  for j in range(reps):
   print(RMSErf[i,j])


print("Tempo de Treinamento: ")
for i in range(len(maxsamples)):
  for j in range(reps):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for i in range(len(maxsamples)):
  for j in range(reps):
    print(temppred[i,j])

"""###Study Max Leaf Nodes"""

#Study Max Leaf Nodes

import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error

maxleafn=[50, 100, 200, 300, 400, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 6000, 7000, 8000, 9000, 10000, None]

reps=5#number of repetitions
shapetest=(len(maxleafn),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error

temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0
for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for maxl in maxleafn:
        rf = RandomForestRegressor(max_leaf_nodes=maxl,max_features=int(used_features/3))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i]} segundos para predizer com o modelo")

        print('Metrics for RF: '+'max_leafnodes='+str(maxl))
        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i]))
        MAErf[i,j]=mean_absolute_error(y_valarea,y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i]))
        RMSErf[i,j]=mean_squared_error(y_valarea,y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i]))

        #Save the model with pickle
#        with open(modelspath+'max_leaf_nodes'+str(maxl)+'rep'+str(j)+'.pkl', 'wb') as f:
#          pickle.dump(rf, f)
        i=i+1

print("R2 Score: ")
for i in range(len(maxleafn)):
  for j in range(reps):
    print(r2_scorerf[i,j])

print("MAE: ")
for i in range(len(maxleafn)):
  for j in range(reps):
    print(MAErf[i,j])

print("RMSErf: ")
for i in range(len(maxleafn)):
  for j in range(reps):
   print(RMSErf[i,j])

print("Tempo de Treinamento: ")
for i in range(len(maxleafn)):
  for j in range(reps):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for i in range(len(maxleafn)):
  for j in range(reps):
    print(temppred[i,j])

"""###Study Min Samples Leaf"""

#Study Min Samples Leaf

import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error

minsamplesleaf=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

reps=5#number of repetitions
shapetest=(len(minsamplesleaf),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error

temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0
for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for minsamples in minsamplesleaf:
        rf = RandomForestRegressor(min_samples_leaf=minsamples,max_features=int(used_features/3))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i]} segundos para predizer com o modelo")


        print('Metrics for RF: '+'minsamplesleaf='+str(minsamples))
        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i]))
        MAErf[i,j]=mean_absolute_error(y_valarea,y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i]))
        RMSErf[i,j]=mean_squared_error(y_valarea,y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i]))

        #Save the model with pickle
    #    with open(modelspath+'min_sample_leafs'+str(minsamples)+'rep'+str(j)+'.pkl', 'wb') as f:
    #      pickle.dump(rf, f)
        i=i+1

print("R2 Score: ")
for i in range(len(minsamplesleaf)):
  for j in range(reps):
    print(r2_scorerf[i,j])

print("MAE: ")
for i in range(len(minsamplesleaf)):
  for j in range(reps):
    print(MAErf[i,j])

print("RMSErf: ")
for i in range(len(minsamplesleaf)):
  for j in range(reps):
   print(RMSErf[i,j])

print("Tempo de Treinamento: ")
for i in range(len(minsamplesleaf)):
  for j in range(reps):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for i in range(len(minsamplesleaf)):
  for j in range(reps):
    print(temppred[i,j])

"""###Study Min Samples Split"""

#Study Min Samples Split

import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error

minsamplessplit=[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

reps=5#number of repetitions
shapetest=(len(minsamplessplit),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição

j=0
for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for minss in minsamplessplit:
        rf = RandomForestRegressor(min_samples_split=minss,max_features=int(used_features/3))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i]} segundos para predizer com o modelo")


        print('Metrics for RF: '+'minsamplesplit='+str(minss))
        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i]))
        MAErf[i,j]=mean_absolute_error(y_valarea,y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i]))
        RMSErf[i,j]=mean_squared_error(y_valarea,y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i]))

        #Save the model with pickle
#        with open(modelspath+'min_sample_split'+str(minss)+'rep'+str(j)+'.pkl', 'wb') as f:
#          pickle.dump(rf, f)
        i=i+1

print("R2 Score: ")
for i in range(len(minsamplessplit)):
  for j in range(reps):
    print(r2_scorerf[i,j])

print("MAE: ")
for i in range(len(minsamplessplit)):
  for j in range(reps):
    print(MAErf[i,j])

print("RMSErf: ")
for i in range(len(minsamplessplit)):
  for j in range(reps):
   print(RMSErf[i,j])

print("Tempo de Treinamento: ")
for i in range(len(minsamplessplit)):
  for j in range(reps):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for i in range(len(minsamplessplit)):
  for j in range(reps):
    print(temppred[i,j])

"""###Study Criterion"""

#Study Criterion

import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error

criteri=["squared_error", "absolute_error", "friedman_mse", "poisson"]
reps=5#number of repetitions
shapetest=(len(criteri),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0
for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for cr in criteri:
        rf = RandomForestRegressor(criterion=cr,max_features=int(used_features/3))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i]} segundos para predizer com o modelo")


        print('Metrics for RF: '+'criterion='+str(cr))
        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i]))
        MAErf[i,j]=mean_absolute_error(y_valarea,y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i]))
        RMSErf[i,j]=mean_squared_error(y_valarea,y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i]))


        #Save the model with pickle
#        with open(modelspath+'criterion'+str(cr)+'rep'+str(j)+'.pkl', 'wb') as f:
#          pickle.dump(rf, f)
        i=i+1

print("R2 Score: ")
for i in range(len(criteri)):
  for j in range(reps):
    print(r2_scorerf[i,j])

print("MAE: ")
for i in range(len(criteri)):
  for j in range(reps):
    print(MAErf[i,j])

print("RMSErf: ")
for i in range(len(criteri)):
  for j in range(reps):
   print(RMSErf[i,j])

print("Tempo de Treinamento: ")
for i in range(len(criteri)):
  for j in range(reps):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for i in range(len(criteri)):
  for j in range(reps):
    print(temppred[i,j])

"""###Study Top Model"""

import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error



rf = RandomForestRegressor(n_estimators=100,
                           max_features=11,
                          criterion='squared_error',
                          max_depth=20,
                           min_samples_split=2,
                           min_samples_leaf=1,
                           max_leaf_nodes=None,
                           max_samples=1.0
                               )

#Study Top Model - along operators

tempo_init=(time.time())#initial training time
rf.fit(x_train, y_train)#fit the RF model
tempo_fint=(time.time())#final training time
temptrain=tempo_fint-tempo_init
print(f"{temptrain} segundos para treinar o modelo")

tempo_inip=(time.time())#initial predict time
y_pred=rf.predict(x_test)#predict in test
tempo_finp=(time.time())#final predict time
temppred=tempo_finp-tempo_inip
print(f"{temppred} segundos para predizer com o modelo")

print('Metrics for RF:')
r2_scorerf=r2_score(y_test,y_pred)#evaluate r2_score
print('R2_Score='+str(r2_scorerf))
MAErf=mean_absolute_error(y_test, y_pred)#evaluate MAE
print('MAE='+str(MAErf))
RMSErf=mean_squared_error(y_test, y_pred, squared=False)#evaluate RMSE
print('RMSE='+str(RMSErf))


#Save the model with pickle
#with open(modelspath+'topmodel.pkl', 'wb') as f:
#  pickle.dump(rf, f)

from pprint import pprint
# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

#Study Top Model - along areas


tempo_init=(time.time())#initial training time
rf.fit(x_trainarea, y_trainarea)#fit the RF model
tempo_fint=(time.time())#final training time
temptrain=tempo_fint-tempo_init
print(f"{temptrain} segundos para treinar o modelo")


#Validation

tempo_inip=(time.time())#initial predict time
y_pred=rf.predict(x_valarea)#predict in test
tempo_finp=(time.time())#final predict time
temppred=tempo_finp-tempo_inip
print(f"{temppred} segundos para predizer com o modelo")

print('Metrics for RF (validation):')
r2_scorerf=r2_score(y_valarea,y_pred)#evaluate r2_score
print('R2_Score='+str(r2_scorerf))
MAErf=mean_absolute_error(y_valarea, y_pred)#evaluate MAE
print('MAE='+str(MAErf))
RMSErf=mean_squared_error(y_valarea, y_pred, squared=False)#evaluate RMSE
print('RMSE='+str(RMSErf))






#Testing
tempo_inip=(time.time())#initial predict time
y_pred=rf.predict(x_testarea)#predict in test
tempo_finp=(time.time())#final predict time
temppred=tempo_finp-tempo_inip
print(f"{temppred} segundos para predizer com o modelo")

print('Metrics for RF (test):')
r2_scorerf=r2_score(y_testarea,y_pred)#evaluate r2_score
print('R2_Score='+str(r2_scorerf))
MAErf=mean_absolute_error(y_testarea, y_pred)#evaluate MAE
print('MAE='+str(MAErf))
RMSErf=mean_squared_error(y_testarea, y_pred, squared=False)#evaluate RMSE
print('RMSE='+str(RMSErf))


#Save the model with pickle
#with open(modelspath+'topmodel.pkl', 'wb') as f:
#  pickle.dump(rf, f)

from pprint import pprint
# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

"""## Parte 2- Combined Hyperparameters - RandomForest Algorithm"""

#First 2 reps
#Study Combination - max_depth+max_samples+max_leaf_nodes
import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error


ndepth=[5, 10, 15, 16]
maxsamples=[0.25, 0.5, 0.7, 0.85]
maxleafn=[400, 1500, 3000, 8000]

reps=2#number of repetitions
shapetest=(len(ndepth)*len(maxsamples)*len(maxleafn),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
oob_scorerf=np.zeros(shapetest)# OOB Score
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0

for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for ndep in ndepth:
    for maxsamp in maxsamples:
      for maxlf in maxleafn:
        rf = RandomForestRegressor(max_depth=ndep,max_samples=maxsamp,max_leaf_nodes=maxlf,n_estimators=800,
                                   max_features=12,min_samples_split=9,criterion='friedman_mse',
                                   min_samples_leaf=1)
        print('Metrics for RF: '+'max_depth='+str(ndep)+'  max_samples='+str(maxsamp)+'  max_leaf_nodes='+str(maxlf))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i,j]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i,j]} segundos para predizer com o modelo")

        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i,j]))
        MAErf[i,j]=mean_absolute_error(y_valarea, y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i,j]))
        RMSErf[i,j]=mean_squared_error(y_valarea, y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i,j]))

        i=i+1

print("R2 Score: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(r2_scorerf[i,j])

print("MAE: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(MAErf[i,j])

print("RMSErf: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
   print(RMSErf[i,j])


print("Tempo de Treinamento: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temppred[i,j])

#Last 3 reps
#Study Combination - max_depth+max_samples+max_leaf_nodes
import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error


ndepth=[5, 10, 15, 16]
maxsamples=[0.25, 0.5, 0.7, 0.85]
maxleafn=[400, 1500, 3000, 8000]

reps=3#number of repetitions
shapetest=(len(ndepth)*len(maxsamples)*len(maxleafn),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
oob_scorerf=np.zeros(shapetest)# OOB Score
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0

for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for ndep in ndepth:
    for maxsamp in maxsamples:
      for maxlf in maxleafn:
        rf = RandomForestRegressor(max_depth=ndep,max_samples=maxsamp,max_leaf_nodes=maxlf,n_estimators=800,
                                   max_features=12,min_samples_split=9,criterion='friedman_mse',
                                   min_samples_leaf=1)
        print('Metrics for RF: '+'max_depth='+str(ndep)+'  max_samples='+str(maxsamp)+'  max_leaf_nodes='+str(maxlf))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i,j]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_valarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i,j]} segundos para predizer com o modelo")

        r2_scorerf[i,j]=r2_score(y_valarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i,j]))
        MAErf[i,j]=mean_absolute_error(y_valarea, y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i,j]))
        RMSErf[i,j]=mean_squared_error(y_valarea, y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i,j]))

        i=i+1

print("R2 Score: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(r2_scorerf[i,j])

print("MAE: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(MAErf[i,j])

print("RMSErf: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
   print(RMSErf[i,j])


print("Tempo de Treinamento: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temppred[i,j])

"""## Parte 3- Combinations applied to the test subset

### ANOVA COMB - piores valores (grupo a)
"""

#Study Combination - max_depth+max_samples+max_leaf_nodes - piores resultados (combs - )
import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error


ndepth=[5]
maxsamples=[0.85, 0.7, 0.5]
maxleafn=[8000, 400, 1500, 3000]

reps=5#number of repetitions
shapetest=(len(ndepth)*len(maxsamples)*len(maxleafn),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
oob_scorerf=np.zeros(shapetest)# OOB Score
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição

j=0

for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for ndep in ndepth:
    for maxsamp in maxsamples:
      for maxlf in maxleafn:
        rf = RandomForestRegressor(max_depth=ndep,max_samples=maxsamp,max_leaf_nodes=maxlf,n_estimators=800,
                                   max_features=12,min_samples_split=9,criterion='friedman_mse',
                                   min_samples_leaf=1)
        print('Metrics for RF: '+'max_depth='+str(ndep)+'  max_samples='+str(maxsamp)+'  max_leaf_nodes='+str(maxlf))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i,j]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_testarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i,j]} segundos para predizer com o modelo")

        r2_scorerf[i,j]=r2_score(y_testarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i,j]))
        MAErf[i,j]=mean_absolute_error(y_testarea, y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i,j]))
        RMSErf[i,j]=mean_squared_error(y_testarea, y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i,j]))

        i=i+1

print("R2 Score: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(r2_scorerf[i,j])

print("MAE: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(MAErf[i,j])

print("RMSErf: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
   print(RMSErf[i,j])


print("Tempo de Treinamento: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temppred[i,j])

"""### ANOVA COMB - melhores valores (grupo k)"""

#Study Combination - max_depth+max_samples+max_leaf_nodes - piores resultados
import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error


ndepth=[15,16]
maxsamples=[0.7, 0.85]
maxleafn=[3000,1500,8000]

reps=5#number of repetitions
shapetest=(len(ndepth)*len(maxsamples)*len(maxleafn),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
oob_scorerf=np.zeros(shapetest)# OOB Score
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0

for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for ndep in ndepth:
    for maxsamp in maxsamples:
      for maxlf in maxleafn:
        rf = RandomForestRegressor(max_depth=ndep,max_samples=maxsamp,max_leaf_nodes=maxlf,n_estimators=800,
                                   max_features=12,min_samples_split=9,criterion='friedman_mse',
                                   min_samples_leaf=1)
        print('Metrics for RF: '+'max_depth='+str(ndep)+'  max_samples='+str(maxsamp)+'  max_leaf_nodes='+str(maxlf))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i,j]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_testarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i,j]} segundos para predizer com o modelo")

        r2_scorerf[i,j]=r2_score(y_testarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i,j]))
        MAErf[i,j]=mean_absolute_error(y_testarea, y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i,j]))
        RMSErf[i,j]=mean_squared_error(y_testarea, y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i,j]))

        i=i+1

print("R2 Score: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(r2_scorerf[i,j])

print("MAE: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(MAErf[i,j])

print("RMSErf: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
   print(RMSErf[i,j])


print("Tempo de Treinamento: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temppred[i,j])

"""### ANOVA FATOR

#### Pior Combinação
"""

#Study Combination - max_depth+max_samples+max_leaf_nodes - pior combinação
import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error


ndepth=[5]
maxsamples=[0.25]
maxleafn=[400]

reps=5#number of repetitions
shapetest=(len(ndepth)*len(maxsamples)*len(maxleafn),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
oob_scorerf=np.zeros(shapetest)# OOB Score
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0

for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for ndep in ndepth:
    for maxsamp in maxsamples:
      for maxlf in maxleafn:
        rf = RandomForestRegressor(max_depth=ndep,max_samples=maxsamp,max_leaf_nodes=maxlf,n_estimators=800,
                                   max_features=12,min_samples_split=9,criterion='friedman_mse',
                                   min_samples_leaf=1)
        print('Metrics for RF: '+'max_depth='+str(ndep)+'  max_samples='+str(maxsamp)+'  max_leaf_nodes='+str(maxlf))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i,j]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_testarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i,j]} segundos para predizer com o modelo")

        r2_scorerf[i,j]=r2_score(y_testarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i,j]))
        MAErf[i,j]=mean_absolute_error(y_testarea, y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i,j]))
        RMSErf[i,j]=mean_squared_error(y_testarea, y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i,j]))

        i=i+1

print("R2 Score: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(r2_scorerf[i,j])

print("MAE: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(MAErf[i,j])

print("RMSErf: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
   print(RMSErf[i,j])


print("Tempo de Treinamento: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temppred[i,j])

"""#### Melhor Combinação"""

#Study Combination - max_depth+max_samples+max_leaf_nodes - melhor combinação - considerando um modelo menos complexo
import pickle#Save models
modelspath='/content/drive/MyDrive/Doutorado - UFBA/modelos_randomforest/'
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, median_absolute_error


ndepth=[15]
maxsamples=[0.85]
maxleafn=[1500]

reps=5#number of repetitions
shapetest=(len(ndepth)*len(maxsamples)*len(maxleafn),reps)
r2_scorerf=np.zeros(shapetest)#r2_score
MAErf=np.zeros(shapetest)#Mean Absolute Error
RMSErf=np.zeros(shapetest)# Root Mean Squared Error
oob_scorerf=np.zeros(shapetest)# OOB Score
temptrain=np.zeros(shapetest)# Tempo de treinamento
temppred=np.zeros(shapetest)# Tempo de predição


j=0

for j in range(reps):
  print('Repetition: '+str(j+1))
  i=0
  for ndep in ndepth:
    for maxsamp in maxsamples:
      for maxlf in maxleafn:
        rf = RandomForestRegressor(max_depth=ndep,max_samples=maxsamp,max_leaf_nodes=maxlf,n_estimators=800,
                                   max_features=12,min_samples_split=9,criterion='friedman_mse',
                                   min_samples_leaf=1)
        print('Metrics for RF: '+'max_depth='+str(ndep)+'  max_samples='+str(maxsamp)+'  max_leaf_nodes='+str(maxlf))
        tempo_init=(time.time())#initial training time
        rf.fit(x_trainarea, y_trainarea)#fit the RF model
        tempo_fint=(time.time())#final training time
        temptrain[i,j]=tempo_fint-tempo_init
        print(f"{temptrain[i,j]} segundos para treinar o modelo")

        tempo_inip=(time.time())#initial predict time
        y_pred=rf.predict(x_testarea)#predict
        tempo_finp=(time.time())#final predict time
        temppred[i,j]=tempo_finp-tempo_inip
        print(f"{temppred[i,j]} segundos para predizer com o modelo")

        r2_scorerf[i,j]=r2_score(y_testarea,y_pred)#evaluate r2_score
        print('R2_Score='+str(r2_scorerf[i,j]))
        MAErf[i,j]=mean_absolute_error(y_testarea, y_pred)#evaluate MAE
        print('MAE='+str(MAErf[i,j]))
        RMSErf[i,j]=mean_squared_error(y_testarea, y_pred, squared=False)#evaluate RMSE
        print('RMSE='+str(RMSErf[i,j]))

        i=i+1

print("R2 Score: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(r2_scorerf[i,j])

print("MAE: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(MAErf[i,j])

print("RMSErf: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
   print(RMSErf[i,j])


print("Tempo de Treinamento: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temptrain[i,j])

print("Tempo de Predição: ")
for j in range(reps):
  print('repetition'+str(j))
  for i in range(len(ndepth)*len(maxsamples)*len(maxleafn)):
    print(temppred[i,j])